"""Domain models for meetings and transcript chunks."""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class MeetingStatus(str, Enum):
    PENDING = "pending"
    ACTIVE = "active"
    PAUSED = "paused"
    FINISHED = "finished"
    FAILED = "failed"


class Meeting(BaseModel):
    meeting_id: str
    company_name: str | None = None
    interview_stage: str | None = None
    created_at: datetime = Field(default_factory=datetime.now)
    started_at: datetime | None = None
    ended_at: datetime | None = None
    status: MeetingStatus = MeetingStatus.PENDING


class TranscriptChunk(BaseModel):
    id: int | None = None  # auto-generated by SQLite
    meeting_id: str
    speaker: str = "Unknown"
    start_time: float
    end_time: float
    confidence: float = 0.0
    text: str
    created_at: datetime | None = None
