"""Domain models for interviews and utterances."""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class InterviewStatus(str, Enum):
    PENDING = "pending"
    ACTIVE = "active"
    COMPLETED = "completed"


class Interview(BaseModel):
    id: str
    company: str | None = None
    stage: str | None = None
    created_at: datetime = Field(default_factory=datetime.now)
    status: InterviewStatus = InterviewStatus.PENDING


class UtteranceStatus(str, Enum):
    QUEUED = "queued"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class Utterance(BaseModel):
    id: int | None = None  # auto-generated by SQLite
    interview_id: str
    speaker: str  # "interviewer" | "candidate"
    start_ms: int
    end_ms: int
    audio_path: str
    status: UtteranceStatus = UtteranceStatus.QUEUED
    confidence: float | None = None
    transcript: str | None = None
    created_at: datetime | None = None
